version: 2
updates:
  # Update ReFrame requirements
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # Update ReFrame documentation requirements
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "monthly"
